name:                xi-ctm
version:             0.1.0.0
github:              "githubuser/xi-ctm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/xi-ctm#readme>

dependencies:
- base >= 4.7 && < 5
- text
- process
- exceptions
- mtl

library:
  source-dirs: src
  default-extensions: Strict, OverloadedStrings
  dependencies:
  - vector

executables:
  xi-ctm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xi-ctm
    - process
    - clock
    default-extensions: Strict, OverloadedStrings

tests:
  xi-ctm-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xi-ctm
    - hspec
    - mtl
    - containers
    - exceptions
    default-extensions: Strict, OverloadedStrings

